import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl text-center">Welcome to Tailwind CSS</h1>
        <div className="flex justify-center">
          <Image src="/logo.svg" alt="Tailwind CSS" width={200} height={200} />
        </div>
        </main>
    </div>
  );
}